# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Description: 'AWS CloudFormation for optimizing AWS Config for AWS Security Hub'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Delivery Channel Configuration
        Parameters:
          - DeliveryChannelName
          - Frequency
      - Label:
          default: Delivery Notifications
        Parameters:
          - TopicArn
          - NotificationEmail
    ParameterLabels:
      DeliveryChannelName:
        default: Configuration delivery channel name
      Frequency:
        default: Snapshot delivery frequency
      TopicArn:
        default: SNS topic name
      NotificationEmail:
        default: Notification Email (optional)
Parameters:
  DeliveryChannelName:
    Type: String
    Default: <Generated>
    Description: The name of the delivery channel.
  Frequency:
    Type: String
    Default: 24hours
    Description: The frequency with which AWS Config delivers configuration snapshots.
    AllowedValues:
      - 1hour
      - 3hours
      - 6hours
      - 12hours
      - 24hours
  TopicArn:
    Type: String
    Default: <New Topic>
    Description: >-
      The Amazon Resource Name (ARN) of the Amazon Simple Notification Service
      (Amazon SNS) topic that AWS Config delivers notifications to. Note:
      Leaving the default value will result in the generation of a new topic.
  NotificationEmail:
    Type: String
    Default: <None>
    Description: Email address for AWS Config notifications (for new topics).
Conditions:
  IsGeneratedDeliveryChannelName: !Equals 
    - !Ref DeliveryChannelName
    - <Generated>
  CreateTopic: !Equals 
    - !Ref TopicArn
    - <New Topic>
  CreateSubscription: !And 
    - !Condition CreateTopic
    - !Not 
      - !Equals 
        - !Ref NotificationEmail
        - <None>
Mappings:
  Settings:
    FrequencyMap:
      1hour: One_Hour
      3hours: Three_Hours
      6hours: Six_Hours
      12hours: Twelve_Hours
      24hours: TwentyFour_Hours
Resources:
  ConfigBucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  ConfigBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${ConfigBucket}'
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 's3:PutObject'
            Resource:
              - !Sub >-
                arn:${AWS::Partition}:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*
          - Sid: AWSConfigBucketSecureTransport
            Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${ConfigBucket}'
              - !Sub 'arn:${AWS::Partition}:s3:::${ConfigBucket}/*'
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': false
  ConfigTopic:
    Condition: CreateTopic
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub 'config-topic-${AWS::AccountId}'
      DisplayName: AWS Config Notification Topic
      KmsMasterKeyId: alias/aws/sns
  ConfigTopicPolicy:
    Condition: CreateTopic
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref ConfigTopic
      PolicyDocument:
        Statement:
          - Sid: AWSConfigSNSPolicy
            Action:
              - 'sns:Publish'
            Effect: Allow
            Resource: !Ref ConfigTopic
            Principal:
              Service:
                - config.amazonaws.com
  EmailNotification:
    Condition: CreateSubscription
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref NotificationEmail
      Protocol: email
      TopicArn: !Ref ConfigTopic
  ConfigRecorderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWS_ConfigRole'
  ConfigRecorderForSecurityHub:
    Type: 'AWS::Config::ConfigurationRecorder'
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      RoleARN: !GetAtt 
        - ConfigRecorderRole
        - Arn
      RecordingGroup:
        AllSupported: false
        IncludeGlobalResourceTypes: false
        ResourceTypes:
          - 'AWS::ACM::Certificate'
          - 'AWS::ApiGateway::Stage'
          - 'AWS::ApiGatewayV2::Stage'
          - 'AWS::AppSync::GraphQLApi'
          - 'AWS::AutoScaling::AutoScalingGroup'
          - 'AWS::AutoScaling::LaunchConfiguration'
          - 'AWS::CloudFormation::Stack'
          - 'AWS::CloudFront::Distribution'
          - 'AWS::CloudWatch::Alarm'
          - 'AWS::CodeBuild::Project'
          - 'AWS::DynamoDB::Table'
          - 'AWS::EC2::EIP'
          - 'AWS::EC2::Instance'
          - 'AWS::EC2::LaunchTemplate'
          - 'AWS::EC2::NetworkAcl'
          - 'AWS::EC2::NetworkInterface'
          - 'AWS::EC2::SecurityGroup'
          - 'AWS::EC2::Subnet'
          - 'AWS::EC2::TransitGateway'
          - 'AWS::EC2::VPNConnection'
          - 'AWS::EC2::Volume'
          - 'AWS::ECR::Repository'
          - 'AWS::ECS::Cluster'
          - 'AWS::ECS::Service'
          - 'AWS::ECS::TaskDefinition'
          - 'AWS::EFS::AccessPoint'
          - 'AWS::EKS::Cluster'
          - 'AWS::ElasticBeanstalk::Environment'
          - 'AWS::ElasticLoadBalancing::LoadBalancer'
          - 'AWS::ElasticLoadBalancingV2::LoadBalancer'
          - 'AWS::Elasticsearch::Domain'
          - 'AWS::IAM::Group'
          - 'AWS::IAM::Policy'
          - 'AWS::IAM::Role'
          - 'AWS::IAM::User'
          - 'AWS::KMS::Key'
          - 'AWS::Kinesis::Stream'
          - 'AWS::Lambda::Function'
          - 'AWS::NetworkFirewall::FirewallPolicy'
          - 'AWS::NetworkFirewall::RuleGroup'
          - 'AWS::OpenSearch::Domain'
          - 'AWS::RDS::DBCluster'
          - 'AWS::RDS::DBClusterSnapshot'
          - 'AWS::RDS::DBInstance'
          - 'AWS::RDS::DBSnapshot'
          - 'AWS::RDS::EventSubscription'
          - 'AWS::Redshift::Cluster'
          - 'AWS::S3::Bucket'
          - 'AWS::SNS::Topic'
          - 'AWS::SQS::Queue'
          - 'AWS::SSM::AssociationCompliance'
          - 'AWS::SSM::PatchCompliance'
          - 'AWS::SageMaker::NotebookInstance'
          - 'AWS::SecretsManager::Secret'
          - 'AWS::StepFunctions::StateMachine'
          - 'AWS::WAF::Rule'
          - 'AWS::WAF::RuleGroup'
          - 'AWS::WAF::WebACL'
          - 'AWS::WAFRegional::Rule'
          - 'AWS::WAFRegional::RuleGroup'
          - 'AWS::WAFRegional::WebACL'
          - 'AWS::WAFv2::WebACL'
  ConfigDeliveryChannel:
    Type: 'AWS::Config::DeliveryChannel'
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      Name: !If 
        - IsGeneratedDeliveryChannelName
        - !Ref 'AWS::NoValue'
        - !Ref DeliveryChannelName
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !FindInMap 
          - Settings
          - FrequencyMap
          - !Ref Frequency
      S3BucketName: !Ref ConfigBucket
      SnsTopicARN: !If 
        - CreateTopic
        - !Ref ConfigTopic
        - !Ref TopicArn